server:
  port: 8082
spring:
  application:
    name: lagou-service-email
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名

  mail:
    host: smtp.163.com
    username: zhulongqiu123@163.com
    password: VBQZKZNTTJRZNEKF
    default-encoding: UTF-8
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          required: true
management:
  endpoints:
    web:
      exposure:
        include: "*"  #所有的接口
  # 暴露健康接口的细节
  endpoint:
    health:
      show-details: always